[workspace]
members = [
    "core",
    # "atomic-node",
    # "atomic-py"
    "examples",
]

[workspace.package]
name = "atomic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
arrow = "53.3.0"
http = { version = "1.1.0" }
async-trait = "0.1.83"
tokio = { version = "1.41.1", features = ["full"] }
hyper = { version = "1.5.1", features = ["full"] }
tokio-stream = "0.1.16"
tokio-util = "0.7.12"
# tokio-compat-02 = "0.2.0"
crossbeam = "0.8.2"
dashmap = "6.1.0"
envy = "^0.4.1"
metrohash = "1.0.7"
regex = "1.11.1"
futures = "0.3.25"
num_cpus = "1.15.0"
# randomness
rand = "0.8.5"
rand_distr = "0.4.3"
rand_pcg = "0.3.1"
simplelog = "0.12.1"
# serialization
bincode = "1.3.3"
# capnp = "0.20.3"
# capnp-futures = "0.20.1"
rkyv = "0.8.9"
serde = { version = "1.0.215", features = ["rc", "derive"] }
serde_closure = "0.3.3"
serde_derive = "1.0.215"
fasthash = "0.4"
uriparse = "0.6.4"
once_cell = "1.17.1"
# dynamic typing
downcast-rs = "1.2.1"
dyn-clone = "1.0.17"

itertools = "0.13.0"
hdrs = "0.3.2"
log = "0.4.20"
# optional features
## aws
urlparse = "0.7.3"
url = "2.5.4"
rusoto_core = { version = "0.48.0" }
rusoto_s3 = { version = "0.48.0" }
parking_lot = "0.12.1"
chrono = "0.4.31"
parquet = "53.3.0"
toml = "0.8.0"
tempfile = "3.14.0"
thiserror = "2.0.3"
statrs = "0.17.1"
erased-serde = "0.4.1" # Type-erased Serialize, Serializer and Deserializer traits
typetag = "0.2" # provides a macro for painless serialization of &dyn Trait objects
uuid = { version = "1.11.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
atomic = { path = "./core" }
