//! Compile-time dispatch registries — one module per subsystem.
//!
//! Every registry here follows the same shape: a `#[proc_macro]` in
//! `atomic-runtime-macros` (`register_shuffle_map!`, `register_state_merge!`, ...)
//! submits an entry via `inventory::submit!` at binary load; the corresponding
//! `Lazy<HashMap<&str, &'static Entry>>` here collects all submitted entries once, the
//! first time it's read — `inventory::iter` already hands out `&'static` references, so
//! the map borrows them directly rather than copying anything out. Each entry type owns
//! its dispatch behavior via a `call`/`build` method, so callers ask the entry to do its
//! job (`entry.call(..)`) rather than pulling a bare `fn` pointer out of it and calling
//! that separately. [`TASK_REGISTRY`] itself — the actual task registry — lives directly
//! in this file, and is the *only* registry for dispatch-by-name handlers: shuffle-map
//! handlers ([`shuffle`]) are `TaskEntry`s in it too, not a separate registry/ABI. [`shuffle`]
//! still owns the shuffle-map handler logic and the unrelated `SHUFFLE_KEY_REGISTRY`
//! (`TypeId` reflection, not dispatch); [`state_merge`] and [`partitioner`] each own one
//! other subsystem's registry end to end.

pub mod partitioner;
pub mod shuffle;
pub mod state_merge;

pub use partitioner::{
    PARTITIONER_REGISTRY, PartitionerEntry, PartitionerFactoryFn, lookup_partitioner,
};
pub use shuffle::{
    HashShuffleWriter, SHUFFLE_KEY_REGISTRY, ShuffleKeyEntry, ShuffleWriteCtx, SortShuffleWriter,
    resolve_shuffle_handler, shuffle_map_handler, sort_shuffle_map_handler,
};
pub use state_merge::{STATE_MERGE_REGISTRY, StateMergeEntry, StateMergeFn};

use atomic_data::distributed::{AgentStepPayload, TaskAction, WireDecode, WireEncode};
use atomic_data::error::DataError;
use once_cell::sync::Lazy;
use std::collections::HashMap;
use std::sync::OnceLock;
use thiserror::Error;

/// Dispatch function generated by the `#[task]` macro: `(action, args, input) -> bytes`.
///
/// The error is a plain `String`, not a typed enum: every `#[task]`-annotated function in
/// every binary that links this crate must match this exact `fn`-pointer signature, so the
/// error type is a fixed part of the macro-generated ABI rather than an internal API choice.
/// `NativeDispatcher::dispatch` converts it into a proper `ComputeError` immediately on
/// return (`runtimes/native.rs`).
pub type TaskHandlerFn = fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>;

/// A compiled-in task dispatch entry.
///
/// Every function annotated with `#[task]` submits one of these via
/// `inventory::submit!` at link time. The worker binary collects them all
/// into [`TASK_REGISTRY`] at startup.
pub struct TaskEntry {
    /// Stable identifier for this task, e.g. `"mycrate::mymod::double::a1b2c3d4"`.
    /// Matches the `task_name` field in [`atomic_data::distributed::TaskEnvelope`].
    pub task_name: &'static str,
    /// FNV-1a hash of the function/closure body tokens, computed at compile time.
    /// Used to build [`REGISTRY_FINGERPRINT`] — a single value that captures
    /// the entire task registry state for driver/worker version checking.
    pub body_hash: u64,
    /// The dispatch function generated by the `#[task]` macro.
    pub handler: TaskHandlerFn,
}

impl TaskEntry {
    pub fn call(
        &self,
        action: &TaskAction,
        payload: &[u8],
        data: &[u8],
    ) -> Result<Vec<u8>, String> {
        (self.handler)(action, payload, data)
    }
}

inventory::collect!(TaskEntry);

/// Global compile-time task registry — built once at startup from all
/// `inventory::submit!(TaskEntry { ... })` calls linked into the binary.
///
/// Keyed by `task_name`. Workers call `TASK_REGISTRY.get(task_name)` to dispatch.
///
/// Panics at startup if two entries share the same `task_name` AND point to different
/// handler addresses (a sign of a copy-paste error in `#[task(name = "…")]`).
/// Identical handlers for the same `task_name` are silently deduplicated — this is the
/// expected case for two `task_fn!` closures with the same body in the same module.
pub static TASK_REGISTRY: Lazy<HashMap<&'static str, &'static TaskEntry>> = Lazy::new(|| {
    let mut map: HashMap<&'static str, &'static TaskEntry> = HashMap::new();
    for entry in inventory::iter::<TaskEntry> {
        match map.get(entry.task_name) {
            // Two entries for the same task_name: allow only if they carry the same
            // body_hash (identical task_fn! bodies). A hash mismatch here means a
            // copy-paste error in `#[task(name = "…")]`.
            Some(existing) if existing.body_hash != entry.body_hash => {
                panic!(
                    "Atomic task registry: duplicate task_name \"{}\" with different bodies.\n\
                         Fix: give each task a unique name.",
                    entry.task_name
                );
            }
            _ => {
                map.insert(entry.task_name, entry);
            }
        }
    }
    map
});

/// A single `u64` that fingerprints the entire compiled-in task registry.
///
/// Computed at startup by sorting all `(task_name, body_hash)` pairs and folding
/// them with FNV-1a. Two binaries with identical task implementations produce
/// the same fingerprint even if compiled independently.
///
/// The driver checks this against each worker's advertised fingerprint during
/// registration. A mismatch means the binaries diverged — redeploy workers.
pub static REGISTRY_FINGERPRINT: Lazy<u64> = Lazy::new(|| {
    const FNV_OFFSET: u64 = 14_695_981_039_346_656_037;
    const FNV_PRIME: u64 = 1_099_511_628_211;

    let mut entries: Vec<(&str, u64)> = inventory::iter::<TaskEntry>
        .into_iter()
        .map(|e| (e.task_name, e.body_hash))
        .collect();
    // Sort for determinism — inventory iteration order is not guaranteed.
    entries.sort_unstable_by_key(|(id, _)| *id);

    entries.iter().fold(FNV_OFFSET, |mut h, (id, hash)| {
        for b in id.as_bytes() {
            h ^= *b as u64;
            h = h.wrapping_mul(FNV_PRIME);
        }
        for b in hash.to_le_bytes() {
            h ^= b as u64;
            h = h.wrapping_mul(FNV_PRIME);
        }
        h
    })
});

/// Failure modes of [`invoke_str_task`], one variant per step of the dispatch.
///
/// `HandlerFailed` carries the plain `String` the dispatch handler itself returns —
/// [`TaskHandlerFn`]'s error type is a fixed part of the macro-generated ABI (see its
/// doc comment), not something this crate controls, so it cannot be wrapped in a
/// `#[source]` (`String` doesn't implement `std::error::Error`).
#[derive(Debug, Error)]
pub enum ToolInvokeError {
    #[error("tool '{0}' is not registered in TASK_REGISTRY")]
    NotRegistered(String),
    #[error("encode tool arg for '{task_name}'")]
    EncodeArg {
        task_name: String,
        #[source]
        source: DataError,
    },
    #[error("tool '{task_name}' handler failed: {message}")]
    HandlerFailed { task_name: String, message: String },
    #[error("decode tool result for '{task_name}'")]
    DecodeResult {
        task_name: String,
        #[source]
        source: DataError,
    },
    #[error("tool '{0}' returned no output")]
    EmptyOutput(String),
}

/// Invoke a registered `fn(String) -> String` `#[task]` by its task_name, using the same
/// `TaskAction::Map` wire encoding the macro generates for that signature.
///
/// Used by `agent_step` tool dispatch (`atomic-nlq`'s `TOOL_CALL:` handling) to call a
/// Rust tool by task_name with one JSON-text argument and get one JSON-text result back —
/// the `fn(String) -> String` shape `AgentStepPayload.tool_refs` requires for Rust tools
/// (see `agent-step-tool-calling` design notes: `serde_json::Value` has no rkyv impl, so
/// the wire-level signature must be `String` in/out).
///
/// Every failure is logged at `warn` before it's returned — the caller (`dispatch_tool` in
/// `atomic-nlq`) feeds the error back into the LLM conversation as plain text rather than
/// propagating it, so this is the only place a broken tool call is visible to an operator.
pub fn invoke_str_task(task_name: &str, arg: String) -> Result<String, ToolInvokeError> {
    let entry = TASK_REGISTRY.get(task_name).ok_or_else(|| {
        log::warn!("invoke_str_task: '{task_name}' is not registered in TASK_REGISTRY");
        ToolInvokeError::NotRegistered(task_name.to_string())
    })?;

    let data = vec![arg].encode_wire().map_err(|source| {
        log::warn!("invoke_str_task: encode tool arg for '{task_name}': {source}");
        ToolInvokeError::EncodeArg {
            task_name: task_name.to_string(),
            source,
        }
    })?;

    let result = entry
        .call(&TaskAction::Map, &[], &data)
        .map_err(|message| {
            log::warn!("invoke_str_task: '{task_name}' handler failed: {message}");
            ToolInvokeError::HandlerFailed {
                task_name: task_name.to_string(),
                message,
            }
        })?;

    let mut out = Vec::<String>::decode_wire(&result).map_err(|source| {
        log::warn!("invoke_str_task: decode tool result for '{task_name}': {source}");
        ToolInvokeError::DecodeResult {
            task_name: task_name.to_string(),
            source,
        }
    })?;

    out.pop().ok_or_else(|| {
        log::warn!("invoke_str_task: '{task_name}' returned no output");
        ToolInvokeError::EmptyOutput(task_name.to_string())
    })
}

/// Object-safe runner for [`StepKind::AgentStep`](atomic_data::distributed::StepKind::AgentStep) ops.
///
/// `atomic-nlq` provides the concrete implementation and installs it via
/// [`register_agent_runner`] at startup — avoiding a direct `atomic-compute →
/// atomic-nlq` dependency. `NativeDispatcher` looks it up in
/// [`AGENT_RUNNER_REGISTRY`] when it sees an `AgentStep` op.
///
/// `run_partition` is synchronous; the implementation may call
/// `tokio::runtime::Handle::current().block_on(...)` because dispatch always
/// runs inside a `spawn_blocking` closure (see `executor.rs`).
pub trait AgentRunner: Send + Sync {
    /// Execute a multi-round agent loop over partition inputs.
    ///
    /// `inputs` is rkyv-encoded `Vec<String>` (or JSON array fallback for Python/JS).
    /// Returns rkyv-encoded `Vec<AgentFindings>` on success, or an error string.
    fn run_partition(&self, payload: &AgentStepPayload, inputs: &[u8]) -> Result<Vec<u8>, String>;
}

/// Global agent runner registry — populated once by [`register_agent_runner`].
///
/// `None` until `register_agent_runner` is called. If `AgentStep` is dispatched
/// without a registered runner the worker fails with a clear error message.
pub static AGENT_RUNNER_REGISTRY: OnceLock<Box<dyn AgentRunner>> = OnceLock::new();

/// Install `runner` as the global agent runner.
///
/// Idempotent: if called more than once (e.g. from `#[pymodule]` / `#[module]`
/// init that runs multiple times in tests), the second call is silently ignored.
pub fn register_agent_runner(runner: Box<dyn AgentRunner>) {
    let _ = AGENT_RUNNER_REGISTRY.set(runner);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_registry_is_accessible() {
        // Registry may be empty in unit tests (no #[task] functions in this crate),
        // but it must be constructible without panicking.
        let _ = &*TASK_REGISTRY;
    }

    #[test]
    fn task_registry_get_unknown_returns_none() {
        assert!(TASK_REGISTRY.get("nonexistent::op").is_none());
    }
}
