//! Shuffle-map dispatch: registries plus the handler logic they point at, owned
//! together in one file (the handler logic used to live in a separate
//! `shuffle_map.rs`, three files away from the registries that reference it —
//! see the `registry` module doc for why they were merged).
//!
//! # Registering a new `(K, V)` pair
//!
//! ```rust,ignore
//! // In main.rs, before any shuffle operations (`reduce_by_key`/`group_by_key`):
//! atomic_compute::register_shuffle_map!(String, u32);
//!
//! // For Ord keys that may be range-partitioned (e.g. via `sort_by_key`), register
//! // the sorted variant instead — it also registers the base hash handler:
//! atomic_compute::register_sort_shuffle_map!(i64, f64);
//! ```
//!
//! `NativeDispatcher` (`runtimes/native.rs`) looks up the shuffle's `(K, V)` dispatch
//! key in [`SHUFFLE_MAP_REGISTRY`] (or [`SORT_SHUFFLE_MAP_REGISTRY`] first, if the
//! shuffle was marked sorted) when it sees `StepKind::ShuffleMap`. The driver looks up
//! [`SHUFFLE_KEY_REGISTRY`] by `TypeId` to embed the right dispatch key in the op.

use std::any::TypeId;
use std::hash::{Hash, Hasher};

use atomic_data::partitioner::PartitionerSchema;
use atomic_data::{data::Data, distributed::WireDecode};
use rustc_hash::FxHasher;

use super::declare_registry;

/// Shuffle-map write handler: `(data, shuffle_id, map_id, num_reduce, partitioner) -> ()`.
///
/// Same `String`-error rationale as [`TaskHandlerFn`](super::TaskHandlerFn): this is a
/// `fn`-pointer ABI shared by every `register_shuffle_map!(K, V)` instantiation,
/// converted to `ComputeError` on return.
pub type ShuffleMapHandlerFn = fn(
    &[u8],
    usize,
    usize,
    usize,
    &atomic_data::partitioner::PartitionerSchema,
) -> Result<(), String>;

declare_registry!(
    /// A compile-time shuffle-write handler registered for a specific `(K, V)` type pair.
    ///
    /// Place `register_shuffle_map!(K, V)` in your binary once per pair used with
    /// `reduce_by_key` or `group_by_key`. The worker binary collects all entries into
    /// [`SHUFFLE_MAP_REGISTRY`] at startup.
    ///
    /// # Handler contract
    ///
    /// `handler(data, shuffle_id, map_partition_id, num_reduce_partitions)`:
    /// - `data`: rkyv-encoded `Vec<(K, V)>` from the preceding pipeline ops
    /// - Partitions elements by `FxHash(K) % num_reduce_partitions`
    /// - Writes each bucket as bincode-encoded `Vec<(K, V)>` to `SHUFFLE_CACHE`
    /// - Returns `Ok(())` on success or an error message
    ShuffleMapEntry {
        /// Function pointer that returns the stable dispatch key for this `(K, V)` pair.
        ///
        /// Generated by `register_shuffle_map!(K, V)` as
        /// `concat!(stringify!(K), "::", stringify!(V))` — a compile-time string literal
        /// that is stable across compiler versions (unlike `std::any::type_name`).
        type_id: fn() -> &'static str,
        /// The actual write handler.
        handler: ShuffleMapHandlerFn,
    },
    /// Global compile-time shuffle-map registry — built once at startup from all
    /// `register_shuffle_map!(K, V)` calls linked into the binary.
    ///
    /// Keyed by the stringify-based key (e.g. `"String::u32"`).
    /// `NativeBackend` uses this when it sees `StepKind::ShuffleMap`.
    SHUFFLE_MAP_REGISTRY: &'static str => ShuffleMapHandlerFn,

    |entry: &ShuffleMapEntry| ((entry.type_id)(), entry.handler)
);

declare_registry!(
    /// A compile-time **sorted** shuffle-write handler for `(K, V)` where `K: Ord`.
    ///
    /// Registered by `register_sort_shuffle_map!(K, V)` (opt-in for ordered keys). When the
    /// driver marks a shuffle as a sort-shuffle, the worker uses this handler to sort each
    /// reduce-partition bucket by key before writing, so the driver-side reduce can k-way merge
    /// sorted runs instead of full-sorting.
    SortShuffleMapEntry {
        /// Stable dispatch key for the `(K, V)` pair (same `"K::V"` string as `ShuffleMapEntry`).
        type_id: fn() -> &'static str,
        /// The sorted write handler.
        handler: ShuffleMapHandlerFn,
    },
    /// Global compile-time **sorted** shuffle-map registry. Keyed by the same `"K::V"` string as
    /// [`SHUFFLE_MAP_REGISTRY`]; an entry exists only for key types where
    /// `register_sort_shuffle_map!(K, V)` was called (i.e. `K: Ord`).
    SORT_SHUFFLE_MAP_REGISTRY: &'static str => ShuffleMapHandlerFn,
    |entry: &SortShuffleMapEntry| ((entry.type_id)(), entry.handler)
);

declare_registry!(
    /// Maps a concrete `(K, V)` `TypeId` to its stable shuffle dispatch key.
    ///
    /// Used by the driver (in `rdd/typed.rs`) to look up the key when building a
    /// `ShuffleMap` pipeline op. The key is the same `stringify!`-based string stored
    /// in [`SHUFFLE_MAP_REGISTRY`], ensuring driver and worker use an identical lookup.
    ///
    /// Submitted by `register_shuffle_map!(K, V)` alongside [`ShuffleMapEntry`].
    ShuffleKeyEntry {
        /// Returns `TypeId::of::<(K, V)>()` — used as the lookup key by the driver.
        type_id: fn() -> TypeId,
        /// The stable dispatch key (e.g. `"String::u32"`).
        key: &'static str,
    },
    /// Global map from `TypeId::of::<(K, V)>()` to the shuffle dispatch key string.
    ///
    /// The driver calls `SHUFFLE_KEY_REGISTRY.get(&TypeId::of::<(K, V)>())` to obtain
    /// the key to embed in a `ShuffleMap` pipeline op payload.
    SHUFFLE_KEY_REGISTRY: TypeId => &'static str,
    |entry: &ShuffleKeyEntry| ((entry.type_id)(), entry.key)
);

/// Generic shuffle-write function for `(K, V)` pairs.
///
/// Called by `NativeBackend` when it sees `StepKind::ShuffleMap`.
/// Decodes the rkyv-encoded `Vec<(K, V)>` input, partitions elements by
/// `FxHash(key) % num_reduce_partitions`, and writes each bucket as
/// bincode-encoded `Vec<(K, V)>` to `SHUFFLE_CACHE`.
///
/// Register this for a specific `(K, V)` pair with `register_shuffle_map!`.
///
/// Returns `Result<(), String>`, not a typed error: this function is assigned to the
/// [`ShuffleMapHandlerFn`] `fn`-pointer type, the dispatch ABI shared by every
/// `register_shuffle_map!(K, V)` instantiation across the binary. `NativeDispatcher`
/// converts the string into a proper `ComputeError` immediately on return (`runtimes/native.rs`).
pub fn shuffle_map_handler<K, V>(
    data: &[u8],
    shuffle_id: usize,
    map_partition_id: usize,
    num_reduce_partitions: usize,
    // Plain hashing ignores the spec; a named custom partitioner (from
    // `partition_by_named`) is reconstructed from it and used instead.
    spec: &PartitionerSchema,
) -> Result<(), String>
where
    K: Data + Clone + Hash + bincode::Encode + bincode::Decode<()> + WireDecode,
    V: Data + Clone + bincode::Encode + bincode::Decode<()> + WireDecode,
    Vec<(K, V)>: WireDecode,
{
    let pairs: Vec<(K, V)> = Vec::<(K, V)>::decode_wire(data)
        .map_err(|e| format!("shuffle_map_handler: decode input: {e}"))?;

    // If the shuffle carried a registered named partitioner, rebuild and use it;
    // otherwise partition by FxHash (deterministic across processes, no seed).
    let custom = spec
        .custom_name()
        .and_then(|name| super::partitioner::lookup_partitioner(name, num_reduce_partitions));

    let mut buckets: Vec<Vec<(K, V)>> = (0..num_reduce_partitions).map(|_| vec![]).collect();

    for (k, v) in pairs {
        let bucket = match &custom {
            Some(p) => p
                .get_partition(&k as &dyn std::any::Any)
                .min(num_reduce_partitions.saturating_sub(1)),
            None => {
                let mut hasher = FxHasher::default();
                k.hash(&mut hasher);
                (hasher.finish() as usize) % num_reduce_partitions
            }
        };
        buckets[bucket].push((k, v));
    }

    let cache = atomic_data::env::get_shuffle_cache()
        .ok_or_else(|| "shuffle_map_handler: SHUFFLE_CACHE not initialized".to_string())?;

    // Encode each reduce-partition bucket once (per-partition framing is preserved in both layouts).
    let encoded: Vec<Vec<u8>> = buckets
        .into_iter()
        .map(|bucket| {
            bincode::encode_to_vec(&bucket, bincode::config::standard())
                .map_err(|e| format!("shuffle_map_handler: encode bucket: {e}"))
        })
        .collect::<Result<_, _>>()?;

    if num_reduce_partitions >= atomic_data::env::sort_shuffle_threshold() {
        // Consolidated (sort-shuffle) layout: one DATA blob + one INDEX for this map task.
        atomic_data::shuffle::cache::write_consolidated(
            cache.as_ref(),
            shuffle_id,
            map_partition_id,
            &encoded,
        )
        .map_err(|e| e.to_string())?;
    } else {
        // Legacy per-bucket layout: one entry per reduce partition.
        for (reduce_id, bytes) in encoded.into_iter().enumerate() {
            cache.insert((shuffle_id, map_partition_id, reduce_id), bytes);
        }
    }

    log::debug!(
        "shuffle_map_handler: wrote {} buckets for shuffle_id={} partition={}",
        num_reduce_partitions,
        shuffle_id,
        map_partition_id
    );
    Ok(())
}

/// Sorted shuffle-write handler for `K: Ord`. Unlike [`shuffle_map_handler`], it partitions using
/// the **real** partitioner reconstructed from the shipped `spec` (range bounds for `sort_by_key`),
/// then sorts each reduce-partition bucket by key — so the driver-side reduce can k-way merge
/// globally-ordered sorted runs. Registered via `register_sort_shuffle_map!`.
pub fn sort_shuffle_map_handler<K, V>(
    data: &[u8],
    shuffle_id: usize,
    map_partition_id: usize,
    num_reduce_partitions: usize,
    spec: &PartitionerSchema,
) -> Result<(), String>
where
    K: atomic_data::data::Data
        + Clone
        + Hash
        + Ord
        + Eq
        + bincode::Encode
        + bincode::Decode<()>
        + WireDecode,
    V: atomic_data::data::Data + Clone + bincode::Encode + bincode::Decode<()> + WireDecode,
    Vec<(K, V)>: WireDecode,
{
    let pairs: Vec<(K, V)> = Vec::<(K, V)>::decode_wire(data)
        .map_err(|e| format!("sort_shuffle_map_handler: decode input: {e}"))?;

    // Reconstruct the RDD's real partitioner from the shipped spec (range bounds → correct global
    // ranges). Hash/Custom specs degrade to hash partitioning.
    let partitioner = spec.into_partitioner::<K>();
    let descending = matches!(
        spec,
        PartitionerSchema::Range {
            ascending: false,
            ..
        }
    );

    let mut buckets: Vec<Vec<(K, V)>> = (0..num_reduce_partitions).map(|_| vec![]).collect();
    for (k, v) in pairs {
        let bucket = partitioner
            .get_partition(&k as &dyn std::any::Any)
            .min(num_reduce_partitions.saturating_sub(1));
        buckets[bucket].push((k, v));
    }

    let cache = atomic_data::env::get_shuffle_cache()
        .ok_or_else(|| "sort_shuffle_map_handler: SHUFFLE_CACHE not initialized".to_string())?;

    // Sort each bucket by key (matching the range direction) → sorted runs for the reduce merge.
    let encoded: Vec<Vec<u8>> = buckets
        .into_iter()
        .map(|mut bucket| {
            if descending {
                bucket.sort_by(|a, b| b.0.cmp(&a.0));
            } else {
                bucket.sort_by(|a, b| a.0.cmp(&b.0));
            }
            bincode::encode_to_vec(&bucket, bincode::config::standard())
                .map_err(|e| format!("sort_shuffle_map_handler: encode bucket: {e}"))
        })
        .collect::<Result<_, _>>()?;

    if num_reduce_partitions >= atomic_data::env::sort_shuffle_threshold() {
        atomic_data::shuffle::cache::write_consolidated(
            cache.as_ref(),
            shuffle_id,
            map_partition_id,
            &encoded,
        )
        .map_err(|e| e.to_string())?;
    } else {
        for (reduce_id, bytes) in encoded.into_iter().enumerate() {
            cache.insert((shuffle_id, map_partition_id, reduce_id), bytes);
        }
    }
    Ok(())
}
