use atomic_data::distributed::TaskAction;
use once_cell::sync::Lazy;
use std::collections::HashMap;

/// A compiled-in task dispatch entry.
///
/// Every function annotated with `#[task]` submits one of these via
/// `inventory::submit!` at link time. The worker binary collects them all
/// into [`TASK_REGISTRY`] at startup.
pub struct TaskEntry {
    /// Stable identifier for this task, e.g. `"mycrate::mymod::double"`.
    /// Matches the `op_id` field in [`atomic_data::distributed::TaskEnvelope`].
    pub op_id: &'static str,
    /// The dispatch function generated by the `#[task]` macro.
    /// Receives the action kind, the action config payload (e.g. fold zero),
    /// and the rkyv-encoded partition data. Returns rkyv-encoded result bytes.
    pub handler: fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>,
}

inventory::collect!(TaskEntry);

/// Global compile-time task registry — built once at startup from all
/// `inventory::submit!(TaskEntry { ... })` calls linked into the binary.
///
/// Keyed by `op_id`. Workers call `TASK_REGISTRY.get(op_id)` to dispatch.
pub static TASK_REGISTRY: Lazy<HashMap<&'static str, fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>>> =
    Lazy::new(|| {
        inventory::iter::<TaskEntry>
            .into_iter()
            .map(|entry| (entry.op_id, entry.handler))
            .collect()
    });

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_registry_is_accessible() {
        // Registry may be empty in unit tests (no #[task] functions in this crate),
        // but it must be constructible without panicking.
        let _ = &*TASK_REGISTRY;
    }

    #[test]
    fn task_registry_get_unknown_returns_none() {
        assert!(TASK_REGISTRY.get("nonexistent::op").is_none());
    }
}
