use atomic_data::distributed::TaskAction;
use once_cell::sync::Lazy;
use std::any::TypeId;
use std::collections::HashMap;

/// A compiled-in task dispatch entry.
///
/// Every function annotated with `#[task]` submits one of these via
/// `inventory::submit!` at link time. The worker binary collects them all
/// into [`TASK_REGISTRY`] at startup.
pub struct TaskEntry {
    /// Stable identifier for this task, e.g. `"mycrate::mymod::double"`.
    /// Matches the `op_id` field in [`atomic_data::distributed::TaskEnvelope`].
    pub op_id: &'static str,
    /// The dispatch function generated by the `#[task]` macro.
    /// Receives the action kind, the action config payload (e.g. fold zero),
    /// and the rkyv-encoded partition data. Returns rkyv-encoded result bytes.
    pub handler: fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>,
}

inventory::collect!(TaskEntry);

/// Global compile-time task registry — built once at startup from all
/// `inventory::submit!(TaskEntry { ... })` calls linked into the binary.
///
/// Keyed by `op_id`. Workers call `TASK_REGISTRY.get(op_id)` to dispatch.
///
/// Panics at startup if two entries share the same `op_id` AND point to different
/// handler addresses (a sign of a copy-paste error in `#[task(name = "…")]`).
/// Identical handlers for the same `op_id` are silently deduplicated — this is the
/// expected case for two `task_fn!` closures with the same body in the same module.
pub static TASK_REGISTRY: Lazy<HashMap<&'static str, fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>>> =
    Lazy::new(|| {
        let mut map: HashMap<&'static str, fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>> = HashMap::new();
        for entry in inventory::iter::<TaskEntry> {
            if let Some(&existing) = map.get(entry.op_id) {
                // Two handlers for the same op_id: allow only if they are the same
                // function (identical task_fn! bodies → same handler pointer).
                if existing as usize != entry.handler as usize {
                    panic!(
                        "Atomic task registry: duplicate op_id \"{}\".\n\
                         Two different handlers are registered for the same key.\n\
                         This is usually caused by copy-pasting a `#[task(name = \"...\")]` \
                         attribute without changing the name.\n\
                         Fix: give each task a unique name.",
                        entry.op_id
                    );
                }
                // Same handler (identical task_fn! body) — silently deduplicate.
            } else {
                map.insert(entry.op_id, entry.handler);
            }
        }
        map
    });

/// A compile-time shuffle-write handler registered for a specific `(K, V)` type pair.
///
/// Place `register_shuffle_map!(K, V)` in your binary once per pair used with
/// `reduce_by_key` or `group_by_key`. The worker binary collects all entries into
/// [`SHUFFLE_MAP_REGISTRY`] at startup.
///
/// # Handler contract
///
/// `handler(data, shuffle_id, map_partition_id, num_reduce_partitions)`:
/// - `data`: rkyv-encoded `Vec<(K, V)>` from the preceding pipeline ops
/// - Partitions elements by `FxHash(K) % num_reduce_partitions`
/// - Writes each bucket as bincode-encoded `Vec<(K, V)>` to `SHUFFLE_CACHE`
/// - Returns `Ok(())` on success or an error message
pub struct ShuffleMapEntry {
    /// Function pointer that returns the stable dispatch key for this `(K, V)` pair.
    ///
    /// Generated by `register_shuffle_map!(K, V)` as
    /// `concat!(stringify!(K), "::", stringify!(V))` — a compile-time string literal
    /// that is stable across compiler versions (unlike `std::any::type_name`).
    pub type_id: fn() -> &'static str,
    /// The actual write handler.
    pub handler: fn(&[u8], usize, usize, usize) -> Result<(), String>,
}

inventory::collect!(ShuffleMapEntry);

/// Global compile-time shuffle-map registry — built once at startup from all
/// `register_shuffle_map!(K, V)` calls linked into the binary.
///
/// Keyed by the stringify-based key (e.g. `"String::u32"`).
/// `NativeBackend` uses this when it sees `TaskAction::ShuffleMap`.
pub static SHUFFLE_MAP_REGISTRY: Lazy<HashMap<&'static str, fn(&[u8], usize, usize, usize) -> Result<(), String>>> =
    Lazy::new(|| {
        inventory::iter::<ShuffleMapEntry>
            .into_iter()
            .map(|entry| ((entry.type_id)(), entry.handler))
            .collect()
    });

/// Maps a concrete `(K, V)` `TypeId` to its stable shuffle dispatch key.
///
/// Used by the driver (in `rdd/typed.rs`) to look up the key when building a
/// `ShuffleMap` pipeline op. The key is the same `stringify!`-based string stored
/// in [`SHUFFLE_MAP_REGISTRY`], ensuring driver and worker use an identical lookup.
///
/// Submitted by `register_shuffle_map!(K, V)` alongside [`ShuffleMapEntry`].
pub struct ShuffleKeyEntry {
    /// Returns `TypeId::of::<(K, V)>()` — used as the lookup key by the driver.
    pub type_id: fn() -> TypeId,
    /// The stable dispatch key (e.g. `"String::u32"`).
    pub key: &'static str,
}

inventory::collect!(ShuffleKeyEntry);

/// Global map from `TypeId::of::<(K, V)>()` to the shuffle dispatch key string.
///
/// The driver calls `SHUFFLE_KEY_REGISTRY.get(&TypeId::of::<(K, V)>())` to obtain
/// the key to embed in a `ShuffleMap` pipeline op payload.
pub static SHUFFLE_KEY_REGISTRY: Lazy<HashMap<TypeId, &'static str>> =
    Lazy::new(|| {
        inventory::iter::<ShuffleKeyEntry>
            .into_iter()
            .map(|entry| ((entry.type_id)(), entry.key))
            .collect()
    });

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_registry_is_accessible() {
        // Registry may be empty in unit tests (no #[task] functions in this crate),
        // but it must be constructible without panicking.
        let _ = &*TASK_REGISTRY;
    }

    #[test]
    fn task_registry_get_unknown_returns_none() {
        assert!(TASK_REGISTRY.get("nonexistent::op").is_none());
    }
}
