use atomic_data::distributed::TaskAction;
use once_cell::sync::Lazy;
use std::any::TypeId;
use std::collections::HashMap;

/// A compiled-in task dispatch entry.
///
/// Every function annotated with `#[task]` submits one of these via
/// `inventory::submit!` at link time. The worker binary collects them all
/// into [`TASK_REGISTRY`] at startup.
pub struct TaskEntry {
    /// Stable identifier for this task, e.g. `"mycrate::mymod::double::a1b2c3d4"`.
    /// Matches the `op_id` field in [`atomic_data::distributed::TaskEnvelope`].
    pub op_id: &'static str,
    /// FNV-1a hash of the function/closure body tokens, computed at compile time.
    /// Used to build [`REGISTRY_FINGERPRINT`] — a single value that captures
    /// the entire task registry state for driver/worker version checking.
    pub body_hash: u64,
    /// The dispatch function generated by the `#[task]` macro.
    pub handler: fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>,
}

inventory::collect!(TaskEntry);

/// Global compile-time task registry — built once at startup from all
/// `inventory::submit!(TaskEntry { ... })` calls linked into the binary.
///
/// Keyed by `op_id`. Workers call `TASK_REGISTRY.get(op_id)` to dispatch.
///
/// Panics at startup if two entries share the same `op_id` AND point to different
/// handler addresses (a sign of a copy-paste error in `#[task(name = "…")]`).
/// Identical handlers for the same `op_id` are silently deduplicated — this is the
/// expected case for two `task_fn!` closures with the same body in the same module.
pub static TASK_REGISTRY: Lazy<
    HashMap<&'static str, fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>>,
> = Lazy::new(|| {
    let mut map: HashMap<&'static str, fn(&TaskAction, &[u8], &[u8]) -> Result<Vec<u8>, String>> =
        HashMap::new();
    for entry in inventory::iter::<TaskEntry> {
        if let Some(&existing) = map.get(entry.op_id) {
            // Two handlers for the same op_id: allow only if they carry the same
            // body_hash (identical task_fn! bodies).  A hash collision here means
            // a copy-paste error in `#[task(name = "…")]`.
            let existing_hash = inventory::iter::<TaskEntry>
                .into_iter()
                .find(|e| e.op_id == entry.op_id)
                .map(|e| e.body_hash)
                .unwrap_or(0);
            if existing_hash != entry.body_hash {
                panic!(
                    "Atomic task registry: duplicate op_id \"{}\" with different bodies.\n\
                         Fix: give each task a unique name.",
                    entry.op_id
                );
            }
            let _ = existing;
        } else {
            map.insert(entry.op_id, entry.handler);
        }
    }
    map
});

/// A single `u64` that fingerprints the entire compiled-in task registry.
///
/// Computed at startup by sorting all `(op_id, body_hash)` pairs and folding
/// them with FNV-1a. Two binaries with identical task implementations produce
/// the same fingerprint even if compiled independently.
///
/// The driver checks this against each worker's advertised fingerprint during
/// registration. A mismatch means the binaries diverged — redeploy workers.
pub static REGISTRY_FINGERPRINT: Lazy<u64> = Lazy::new(|| {
    const FNV_OFFSET: u64 = 14_695_981_039_346_656_037;
    const FNV_PRIME: u64 = 1_099_511_628_211;

    let mut entries: Vec<(&str, u64)> = inventory::iter::<TaskEntry>
        .into_iter()
        .map(|e| (e.op_id, e.body_hash))
        .collect();
    // Sort for determinism — inventory iteration order is not guaranteed.
    entries.sort_unstable_by_key(|(id, _)| *id);

    entries.iter().fold(FNV_OFFSET, |mut h, (id, hash)| {
        for b in id.as_bytes() {
            h ^= *b as u64;
            h = h.wrapping_mul(FNV_PRIME);
        }
        for b in hash.to_le_bytes() {
            h ^= b as u64;
            h = h.wrapping_mul(FNV_PRIME);
        }
        h
    })
});

/// A compile-time shuffle-write handler registered for a specific `(K, V)` type pair.
///
/// Place `register_shuffle_map!(K, V)` in your binary once per pair used with
/// `reduce_by_key` or `group_by_key`. The worker binary collects all entries into
/// [`SHUFFLE_MAP_REGISTRY`] at startup.
///
/// # Handler contract
///
/// `handler(data, shuffle_id, map_partition_id, num_reduce_partitions)`:
/// - `data`: rkyv-encoded `Vec<(K, V)>` from the preceding pipeline ops
/// - Partitions elements by `FxHash(K) % num_reduce_partitions`
/// - Writes each bucket as bincode-encoded `Vec<(K, V)>` to `SHUFFLE_CACHE`
/// - Returns `Ok(())` on success or an error message
pub struct ShuffleMapEntry {
    /// Function pointer that returns the stable dispatch key for this `(K, V)` pair.
    ///
    /// Generated by `register_shuffle_map!(K, V)` as
    /// `concat!(stringify!(K), "::", stringify!(V))` — a compile-time string literal
    /// that is stable across compiler versions (unlike `std::any::type_name`).
    pub type_id: fn() -> &'static str,
    /// The actual write handler.
    pub handler: fn(
        &[u8],
        usize,
        usize,
        usize,
        &atomic_data::partitioner::PartitionerSchema,
    ) -> Result<(), String>,
}

inventory::collect!(ShuffleMapEntry);

/// Global compile-time shuffle-map registry — built once at startup from all
/// `register_shuffle_map!(K, V)` calls linked into the binary.
///
/// Keyed by the stringify-based key (e.g. `"String::u32"`).
/// `NativeBackend` uses this when it sees `TaskAction::ShuffleMap`.
pub static SHUFFLE_MAP_REGISTRY: Lazy<
    HashMap<
        &'static str,
        fn(
            &[u8],
            usize,
            usize,
            usize,
            &atomic_data::partitioner::PartitionerSchema,
        ) -> Result<(), String>,
    >,
> = Lazy::new(|| {
    inventory::iter::<ShuffleMapEntry>
        .into_iter()
        .map(|entry| ((entry.type_id)(), entry.handler))
        .collect()
});

/// A compile-time **sorted** shuffle-write handler for `(K, V)` where `K: Ord`.
///
/// Registered by `register_sort_shuffle_map!(K, V)` (opt-in for ordered keys). When the
/// driver marks a shuffle as a sort-shuffle, the worker uses this handler to sort each
/// reduce-partition bucket by key before writing, so the driver-side reduce can k-way merge
/// sorted runs instead of full-sorting.
pub struct SortShuffleMapEntry {
    /// Stable dispatch key for the `(K, V)` pair (same `"K::V"` string as `ShuffleMapEntry`).
    pub type_id: fn() -> &'static str,
    /// The sorted write handler.
    pub handler: fn(
        &[u8],
        usize,
        usize,
        usize,
        &atomic_data::partitioner::PartitionerSchema,
    ) -> Result<(), String>,
}

inventory::collect!(SortShuffleMapEntry);

/// Global compile-time **sorted** shuffle-map registry. Keyed by the same `"K::V"` string as
/// [`SHUFFLE_MAP_REGISTRY`]; an entry exists only for key types where
/// `register_sort_shuffle_map!(K, V)` was called (i.e. `K: Ord`).
pub static SORT_SHUFFLE_MAP_REGISTRY: Lazy<
    HashMap<
        &'static str,
        fn(
            &[u8],
            usize,
            usize,
            usize,
            &atomic_data::partitioner::PartitionerSchema,
        ) -> Result<(), String>,
    >,
> = Lazy::new(|| {
    inventory::iter::<SortShuffleMapEntry>
        .into_iter()
        .map(|entry| ((entry.type_id)(), entry.handler))
        .collect()
});

/// Maps a concrete `(K, V)` `TypeId` to its stable shuffle dispatch key.
///
/// Used by the driver (in `rdd/typed.rs`) to look up the key when building a
/// `ShuffleMap` pipeline op. The key is the same `stringify!`-based string stored
/// in [`SHUFFLE_MAP_REGISTRY`], ensuring driver and worker use an identical lookup.
///
/// Submitted by `register_shuffle_map!(K, V)` alongside [`ShuffleMapEntry`].
pub struct ShuffleKeyEntry {
    /// Returns `TypeId::of::<(K, V)>()` — used as the lookup key by the driver.
    pub type_id: fn() -> TypeId,
    /// The stable dispatch key (e.g. `"String::u32"`).
    pub key: &'static str,
}

inventory::collect!(ShuffleKeyEntry);

/// Global map from `TypeId::of::<(K, V)>()` to the shuffle dispatch key string.
///
/// The driver calls `SHUFFLE_KEY_REGISTRY.get(&TypeId::of::<(K, V)>())` to obtain
/// the key to embed in a `ShuffleMap` pipeline op payload.
pub static SHUFFLE_KEY_REGISTRY: Lazy<HashMap<TypeId, &'static str>> = Lazy::new(|| {
    inventory::iter::<ShuffleKeyEntry>
        .into_iter()
        .map(|entry| ((entry.type_id)(), entry.key))
        .collect()
});

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_registry_is_accessible() {
        // Registry may be empty in unit tests (no #[task] functions in this crate),
        // but it must be constructible without panicking.
        let _ = &*TASK_REGISTRY;
    }

    #[test]
    fn task_registry_get_unknown_returns_none() {
        assert!(TASK_REGISTRY.get("nonexistent::op").is_none());
    }
}
