/// WASM entrypoint helper called by `#[task]`-generated code.
///
/// Takes a (ptr, len) pair pointing at rkyv-encoded input bytes in WASM linear
/// memory, decodes the input, calls the handler, encodes the output, copies it
/// into linear memory via `alloc`, and returns the packed `(result_ptr << 32) | result_len`.
///
/// # Safety
/// `ptr` and `ptr+len` must be valid readable addresses in WASM linear memory.
#[cfg(target_arch = "wasm32")]
pub unsafe fn call_wasm<I, O, F>(ptr: i32, len: i32, handler: F) -> i64
where
    I: rkyv::Archive + for<'a> rkyv::Deserialize<I, rkyv::de::Pool>,
    <I as rkyv::Archive>::Archived:
        rkyv::Deserialize<I, rkyv::de::Pool>
        + for<'a> rkyv::bytecheck::CheckBytes<rkyv::api::high::HighValidator<'a, rkyv::rancor::Error>>,
    O: rkyv::Serialize<rkyv::api::high::HighSerializer<rkyv::util::AlignedVec, rkyv::ser::allocator::ArenaHandle<'static>, rkyv::rancor::Error>>,
    F: Fn(I) -> O,
{
    let bytes = core::slice::from_raw_parts(ptr as *const u8, len as usize);

    let input: I = rkyv::from_bytes::<I, rkyv::rancor::Error>(bytes)
        .expect("atomic-runtime: wasm rkyv decode failed");

    let output = handler(input);

    let out_bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&output)
        .expect("atomic-runtime: wasm rkyv encode failed")
        .to_vec();

    let out_len = out_bytes.len();

    // Allocate output buffer in WASM linear memory and copy bytes in.
    // `alloc` is the bump allocator generated by the #[task] macro.
    extern "C" {
        fn alloc(len: i32) -> i32;
    }
    let out_ptr = alloc(out_len as i32);
    core::ptr::copy_nonoverlapping(
        out_bytes.as_ptr(),
        out_ptr as *mut u8,
        out_len,
    );

    // Pack (result_ptr << 32) | result_len — matches what WasmBackend::execute_guest expects.
    ((out_ptr as i64) << 32) | (out_len as i64)
}

/// Like [`call_wasm`] but uses JSON (serde_json) instead of rkyv.
///
/// Called by `#[task(json)]`-generated WASM entrypoints. The input bytes are
/// a JSON payload; the output is also JSON.
///
/// # Safety
/// `ptr` and `ptr+len` must be valid readable addresses in WASM linear memory.
#[cfg(target_arch = "wasm32")]
pub unsafe fn call_wasm_json<I, O, F>(ptr: i32, len: i32, handler: F) -> i64
where
    I: serde::de::DeserializeOwned,
    O: serde::Serialize,
    F: Fn(I) -> O,
{
    let bytes = core::slice::from_raw_parts(ptr as *const u8, len as usize);

    let input: I = serde_json::from_slice(bytes)
        .expect("atomic-runtime: wasm json decode failed");

    let output = handler(input);

    let out_bytes = serde_json::to_vec(&output)
        .expect("atomic-runtime: wasm json encode failed");

    let out_len = out_bytes.len();

    extern "C" {
        fn alloc(len: i32) -> i32;
    }
    let out_ptr = alloc(out_len as i32);
    core::ptr::copy_nonoverlapping(
        out_bytes.as_ptr(),
        out_ptr as *mut u8,
        out_len,
    );

    ((out_ptr as i64) << 32) | (out_len as i64)
}
