/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Accumulator {
  /** Add a delta using the merge function (if set) or default add logic. */
  add(delta: JV): void
  /** Return the current accumulated value. */
  value(): JV
  /** Reset accumulator to its initial value. */
  reset(): void
}

/** Queue handle for injecting test batches into a `testQueueStream`. */
export declare class BatchQueue {
  /** Enqueue a JavaScript array as the next batch. */
  push(batch: Array<JV>): void
}
export type JsBatchQueue = BatchQueue

export declare class BroadcastVar {
  /** Deserialize and return the broadcast value. */
  value(): any
}

/**
 * The Atomic execution context for JavaScript.
 *
 * Entry point for creating RDDs. In local mode (default) transformations run
 * eagerly in the Node.js thread. In distributed mode (set
 * `ATOMIC_DEPLOYMENT_MODE=distributed`) the context dispatches pipeline ops to
 * workers over TCP.
 *
 * ```javascript
 * const { Context } = require('@atomic-compute/js');
 * const ctx = new Context();
 * const result = ctx.parallelize([1, 2, 3, 4])
 *   .map(x => x * 2)
 *   .filter(x => x > 4)
 *   .collect();
 * // [6, 8]
 * ```
 */
export declare class Context {
  /**
   * Create an Atomic context.
   *
   * @param defaultParallelism - Default number of partitions when not
   *   specified on individual operations. Defaults to the number of logical CPUs.
   */
  constructor(defaultParallelism?: number | undefined | null)
  /**
   * Distribute a JavaScript array as an RDD.
   *
   * @param data - Any JSON-serializable JavaScript array.
   * @param numPartitions - Number of partitions. Defaults to `defaultParallelism`.
   */
  parallelize(data: Array<any>, numPartitions?: number | undefined | null): JsRdd
  /**
   * Create an RDD of lines from a text file or S3 object.
   *
   * Accepts local paths (`/path/to/file`, `file:///path`) and, when built
   * with the `s3` feature, S3 URIs (`s3://bucket/key`).  A directory path
   * or S3 prefix produces one partition per file/object.
   *
   * @param path - Local path or `s3://bucket/key` URI.
   */
  textFile(path: string): JsRdd
  /**
   * Create an RDD of integers in `[start, end)` with optional `step`.
   *
   * @param start - Range start (inclusive).
   * @param end - Range end (exclusive).
   * @param step - Increment (default 1).
   * @param numPartitions - Number of partitions. Defaults to `defaultParallelism`.
   */
  range(start: number, end: number, step?: number | undefined | null, numPartitions?: number | undefined | null): JsRdd
  /** Return the default number of partitions (CPU count or constructor value). */
  defaultParallelism(): number
  /**
   * Stop the context and release resources.
   *
   * In distributed mode, sends a graceful-shutdown signal to every worker.
   */
  stop(): void
  /**
   * Broadcast a JSON-serializable value to all tasks.
   *
   * The returned `BroadcastVar` holds a serialized copy of the value that
   * any task can read via `.value()`.
   */
  broadcast(value: any): BroadcastVar
  /**
   * Create an accumulator with an initial numeric, array, or string value.
   *
   * An optional `mergeFn(current, delta) -> newValue` overrides the default
   * add logic (numeric sum, string concat, array append).
   *
   * Call `.add(delta)` from within `forEach` / `map` etc. to accumulate
   * values.  The accumulator is not automatically reset between actions.
   */
  accumulator(zero: any, mergeFn?: ((arg: [any, any]) => any) | undefined | null): Accumulator
}
export type JsContext = Context

/**
 * A lazy structured dataset produced by `SqlContext.sql()`.
 *
 * Call `collect()`, `count()`, or `show()` to trigger execution.
 *
 * @example
 * ```typescript
 * const df = ctx.sql("SELECT id, value FROM t WHERE value > 10");
 * const rows = df.collect();  // Array<Record<string, unknown>>
 * ```
 */
export declare class DataFrame {
  /**
   * Execute the query and return all rows as an array of objects.
   *
   * Each object maps column name → value (number, string, boolean, or null).
   */
  collect(): Array<any>
  /**
   * Execute the query and return the result as Arrow IPC stream bytes.
   *
   * The returned `Buffer` is an Arrow IPC *stream* — read it on the JS side
   * with `apache-arrow`'s `tableFromIPC(buffer)`. Mirrors `to_arrow()` in the
   * Python bindings (which returns a PyArrow Table).
   *
   * ```js
   * import { tableFromIPC } from "apache-arrow";
   * const table = tableFromIPC(df.toArrow());
   * ```
   */
  toArrow(): Buffer
  /** Execute and print a formatted table to stdout (default: 20 rows). */
  show(): void
  /** Execute and print the first `n` rows to stdout. */
  showLimit(n: number): void
  /** Return the total number of rows. */
  count(): number
  /**
   * Filter rows using a SQL WHERE-clause expression.
   *
   * @param expr - SQL expression string, e.g. `"amount > 100"`.
   *
   * @example
   * ```typescript
   * const expensive = df.filter("amount > 100");
   * ```
   */
  filter(expr: string): DataFrame
  /**
   * Keep only the specified columns.
   *
   * @param columns - Array of column name strings.
   *
   * @example
   * ```typescript
   * const slim = df.select(["id", "name"]);
   * ```
   */
  select(columns: Array<string>): DataFrame
  /** Limit the result to the first `n` rows. */
  limit(n: number): DataFrame
  /**
   * Sort by a column name.
   *
   * @param col - Column name to sort by.
   * @param ascending - `true` (default) for ascending, `false` for descending.
   */
  sort(col: string, ascending?: boolean | undefined | null): DataFrame
  /**
   * Return a JSON object mapping column name → Arrow type string.
   *
   * @example
   * ```typescript
   * df.schema()  // → { "id": "Int64", "name": "Utf8", "amount": "Float64" }
   * ```
   */
  schema(): any
  /**
   * Write all rows to a Parquet file or directory.
   *
   * @param path - Output directory path.
   *
   * @example
   * ```typescript
   * await df.writeParquet("/tmp/output/");
   * ```
   */
  writeParquet(path: string): void
  /**
   * Write all rows to CSV files in a directory.
   *
   * @param path - Output directory path.
   *
   * @example
   * ```typescript
   * await df.writeCsv("/tmp/output/");
   * ```
   */
  writeCsv(path: string): void
}
export type JsDataFrame = DataFrame

/** A lazy handle to a DStream transform chain (Node.js). */
export declare class DStream {
  map(f: (arg: JV) => JV): DStream
  filter(f: (arg: JV) => boolean): DStream
  flatMap(f: (arg: JV) => Array<JV>): DStream
  reduceByKey(f: (arg: [JV, JV]) => JV): DStream
  groupByKey(): DStream
  join(other: DStream): DStream
  leftOuterJoin(other: DStream): DStream
  updateStateByKey(f: (arg: [Array<JV>, JV | undefined | null]) => JV | null): DStream
  mapValues(f: (arg: JV) => JV): DStream
  /**
   * Return a new DStream that unions the parent's batches over a sliding window.
   *
   * `windowMs`  — how far back (in milliseconds) to include batches.
   * `slideMs`   — accepted for API compatibility; every `runOneBatch()` call
   *               advances the window by one tick in this in-process model.
   */
  window(windowMs: number, slideMs: number): DStream
}
export type JsDStream = DStream

export declare class Graph {
  /**
   * Create a graph from explicit vertex and edge lists.
   *
   * @param vertices - Array of [vertexId, weight] tuples
   * @param edges    - Array of [srcId, dstId, weight] tuples
   */
  constructor(vertices: Array<Array<any>>, edges: Array<Array<any>>)
  /** Return the number of vertices. */
  numVertices(): number
  /** Return the number of edges. */
  numEdges(): number
  /** Return all vertices as an array of `[vertexId, data]` pairs. */
  vertices(): Array<[number, number]>
  /** Return all edges as an array of `[srcId, dstId, weight]` triples. */
  edges(): Array<[number, number, number]>
  /** Run PageRank. Returns Record<string, number> (keys are vertex ID strings). */
  pageRank(numIter: number, resetProb: number): Record<string, number>
  /** Connected components (weakly). Returns Record<string, number>. */
  connectedComponents(): Record<string, number>
  /** Strongly connected components (Tarjan's). Returns Record<string, number>. */
  stronglyConnectedComponents(): Record<string, number>
  /** Label propagation community detection. Returns Record<string, number>. */
  labelPropagation(maxIter: number): Record<string, number>
  /** Triangle count per vertex. Returns Record<string, number>. */
  triangleCount(): Record<string, number>
  /**
   * Shortest path distances from landmarks.
   * Returns Record<string, Record<string, number>>.
   */
  shortestPath(landmarks: Array<number>): Record<string, Record<string, number>>
  /**
   * Run a custom Pregel vertex-centric computation.
   *
   * All vertex data, edge data, and messages are `number` (f64) values.
   *
   * @param initialMsg    - Message sent to every vertex before superstep 0.
   * @param maxIterations - Maximum number of supersteps.
   * @param vprog         - `(vertexId: number, vertexData: number, msg: number) => number`
   *                        Updates vertex attribute given an incoming message.
   * @param sendMsg       - `(srcId, srcData, dstId, dstData, edgeData) => Array<[number, number]>`
   *                        Returns `[targetVertexId, message]` pairs to send.
   *                        Use `srcId` or `dstId` as the target.
   * @param mergeMsg      - `(msgA: number, msgB: number) => number`
   *                        Commutative combiner for messages to the same vertex.
   *
   * Returns a new `Graph` with updated vertex attributes.
   *
   * @example
   * ```javascript
   * // Propagate minimum vertex ID to all reachable vertices.
   * const result = g.runPregelF64(
   *   Infinity, 10,
   *   (vid, vd, msg) => Math.min(vd, msg),
   *   (si, sd, di, dd, ed) => sd < dd ? [[di, sd]] : [],
   *   (a, b) => Math.min(a, b),
   * );
   * ```
   */
  runPregelF64(initialMsg: number, maxIterations: number, vprog: (arg0: number, arg1: number, arg2: number) => number, sendMsg: PregelSendFn, mergeMsg: (arg0: number, arg1: number) => number): Graph
}
export type JsGraph = Graph

/**
 * A distributed dataset (RDD) of JavaScript values.
 *
 * In local mode all transformations execute eagerly in the Node.js thread.
 * In distributed mode transformations build a lazy pipeline that is dispatched
 * to workers as a single `TaskEnvelope` per partition when an action is called.
 *
 * ```javascript
 * const rdd = ctx.parallelize([1, 2, 3, 4]);
 * const result = rdd
 *   .map(x => x * 2)
 *   .filter(x => x > 4)
 *   .collect();
 * // [6, 8]
 * ```
 */
export declare class JsRdd {
  /** Return all elements as a JavaScript array. */
  collect(): Array<JsonValue>
  /** Return the number of elements. */
  count(): number
  /** Return the first element. Throws if the RDD is empty. */
  first(): JsonValue
  /** Return the first `n` elements. */
  take(n: number): Array<JsonValue>
  /** Aggregate all elements using `f(acc, element) => acc`. Throws if empty. */
  reduce(f: (arg0: JsonValue, arg1: JsonValue) => JsonValue): JsonValue
  /** Aggregate with an initial value using `f(acc, element) => acc`. */
  fold(zero: JsonValue, f: (arg0: JsonValue, arg1: JsonValue) => JsonValue): JsonValue
  /** Apply `f` to each element for side effects. */
  forEach(f: (arg: JsonValue) => unknown): void
  /** Apply `f` to each logical partition for side effects. */
  forEachPartition(f: (arg: Array<JsonValue>) => unknown): void
  /** Count occurrences of each distinct element. Returns `{element: count}`. */
  countByValue(): JsonValue
  /** Count elements per key in a pair RDD. Returns `{key: count}`. */
  countByKey(): JsonValue
  /** Return true if the RDD has no elements. */
  isEmpty(): boolean
  /** Return the maximum element. Optional comparator `f(a, b) => number` (positive = a > b). */
  max(comparator?: ((arg0: JsonValue, arg1: JsonValue) => number) | undefined | null): JsonValue
  /** Return the minimum element. Optional comparator `f(a, b) => number` (negative = a < b). */
  min(comparator?: ((arg0: JsonValue, arg1: JsonValue) => number) | undefined | null): JsonValue
  /**
   * Write each element as a line to `path`.
   *
   * Accepts a local file path or, when built with the `s3` feature, an
   * S3 URI (`s3://bucket/prefix`).
   */
  saveAsTextFile(path: string): void
  /**
   * Two-phase aggregation: `seqFn(acc, elem) => acc` within partitions,
   * `combFn(acc, acc) => acc` across partition results.
   */
  aggregate(zero: JsonValue, seqFn: (arg0: JsonValue, arg1: JsonValue) => JsonValue, combFn: (arg0: JsonValue, arg1: JsonValue) => JsonValue): JsonValue
  /** Return elements divided into `num_partitions` logical partition arrays. */
  glom(): Array<Array<JsonValue>>
  /** Mark this RDD to be cached in memory on first action (no-op in local mode). */
  cache(): JsRdd
  /** Mark this RDD to be persisted (alias for `cache` in local mode). */
  persist(): JsRdd
  /** Remove this RDD from the cache (no-op in local mode). */
  unpersist(): JsRdd
  /**
   * Write all elements to `{path}/checkpoint.json` and return a new RDD
   * backed by the same elements.
   *
   * The write is atomic: data is first written to `{path}/checkpoint.json.tmp`
   * and then renamed to `{path}/checkpoint.json`.
   */
  checkpoint(path: string): JsRdd
  /** Return the logical number of partitions. */
  get numPartitions(): number
  length(): number
  /**
   * Run a framework-native, multi-round LLM agent loop over each partition.
   *
   * `config` is an object describing the agent:
   *   - `model` (string, required)            — e.g. `"gpt-4o-mini"`
   *   - `systemPrompt` (string, required)      — the agent's task description
   *   - `maxRounds` (number, default 2)        — plan→execute→evaluate rounds per input
   *   - `provider` (string, default "openai")  — `"openai"` or `"anthropic"`
   *   - `toolRefs` (string[], default [])      — tool names the agent may reference
   *   - `outputSchema` (string, optional)      — JSON schema for best-effort output validation
   *   - `maxTokensTotal` (number, optional)    — token budget across all inputs in a partition
   *
   * Each RDD element must be a string. Returns an array of objects, one per input element:
   *   `{ inputId, answer, rounds, confidence, budgetExceeded }`
   *
   * Requires the agent runner to be registered (done automatically at module load)
   * and one of `OPENAI_API_KEY` / `ANTHROPIC_API_KEY` set in the environment.
   */
  agentStep(config: JsonValue): Array<{ inputId: number, answer: string, rounds: number, confidence: number, budgetExceeded: boolean }>
  /** Group `[key, value]` pairs by key → `[key, [values]]` pairs. */
  groupByKey(): JsRdd
  /** Aggregate values with the same key using `f(acc, value) => acc`. */
  reduceByKey(f: (arg0: JsonValue, arg1: JsonValue) => JsonValue): JsRdd
  /** Extract the key from each `[key, value]` pair. */
  keys(): JsRdd
  /** Extract the value from each `[key, value]` pair. */
  values(): JsRdd
  /** Return all values associated with `key` from a pair RDD. */
  lookup(key: JsonValue): Array<JsonValue>
  /**
   * Inner join two pair RDDs on their first element (key).
   *
   * Both RDDs must contain `[key, value]` arrays.
   * Emits `[key, [left_value, right_value]]` for each matching key pair.
   *
   * In distributed mode the right side (if already in driver memory) is embedded
   * in the worker closure as JSON — each worker joins against its left partition
   * without collecting data to the driver first.
   */
  join(other: JsRdd): JsRdd
  /**
   * Left outer join two pair RDDs on their first element (key).
   *
   * Emits `[key, [left_value, right_value]]` for matched keys and
   * `[key, [left_value, null]]` for unmatched left keys.
   *
   * In distributed mode the right side is embedded in the worker closure as JSON.
   */
  leftOuterJoin(other: JsRdd): JsRdd
  /** Return the top `n` elements (largest first). Optional comparator `f(a, b) => number`. */
  top(n: number, comparator?: ((arg0: JsonValue, arg1: JsonValue) => number) | undefined | null): Array<JsonValue>
  /** Return the `n` smallest elements. Optional comparator `f(a, b) => number`. */
  takeOrdered(n: number, comparator?: ((arg0: JsonValue, arg1: JsonValue) => number) | undefined | null): Array<JsonValue>
  /**
   * Sort elements by a key extracted via `key_fn(element)`.
   *
   * `ascending` defaults to `true`. The key function is called on each
   * element; results are compared using JSON ordering (numbers numerically,
   * strings lexicographically).
   */
  sortBy(keyFn: (arg: JsonValue) => JsonValue, ascending?: boolean | undefined | null): JsRdd
  /**
   * Sort `[key, value]` pair elements by their first element (key).
   *
   * `ascending` defaults to `true`. Keys are compared using JSON ordering.
   *
   * In distributed mode each worker sorts its partition; the driver k-way merges
   * the N sorted runs. Not a globally range-partitioned shuffle sort, but removes
   * the O(N log N) bottleneck on the driver. `sort_by_key` is an action: dispatch
   * happens immediately and `self` stays reusable for further transforms/actions.
   */
  sortByKey(ascending?: boolean | undefined | null): JsRdd
  /** Apply `f` to each element, returning a new RDD. */
  map(f: (arg: JsonValue) => JsonValue): JsRdd
  /** Keep only elements for which `f` returns truthy. */
  filter(f: (arg: JsonValue) => boolean): JsRdd
  /** Apply `f` to each element and flatten (f must return an Array). */
  flatMap(f: (arg: JsonValue) => Array<JsonValue>): JsRdd
  /** Apply `f` only to the value in each `[key, value]` pair. */
  mapValues(f: (arg: JsonValue) => JsonValue): JsRdd
  /** Apply `f` to each value in `[key, value]` pairs and flatten. */
  flatMapValues(f: (arg: JsonValue) => Array<JsonValue>): JsRdd
  /** Produce `[f(element), element]` pairs. */
  keyBy(f: (arg: JsonValue) => JsonValue): JsRdd
  /** Group elements by `f(element)` → `[key, [elements]]` pairs. */
  groupBy(f: (arg: JsonValue) => JsonValue): JsRdd
  /** Apply `f` to each logical partition (array of elements), returning a flattened RDD. */
  mapPartitions(f: (arg: Array<JsonValue>) => Array<JsonValue>): JsRdd
  /** Merge two RDDs into one. */
  union(other: JsRdd): JsRdd
  /** Zip two equal-length RDDs into an RDD of `[a, b]` pairs. */
  zip(other: JsRdd): JsRdd
  /** Compute the Cartesian product of two RDDs as `[a, b]` pairs. */
  cartesian(other: JsRdd): JsRdd
  /** Reduce to `n` logical partitions. */
  coalesce(n: number): JsRdd
  /** Change partition count (alias for `coalesce`). */
  repartition(n: number): JsRdd
  /** Remove duplicate elements. */
  distinct(): JsRdd
  /** Return elements in `self` that are not in `other`. */
  subtract(other: JsRdd): JsRdd
  /** Return elements present in both `self` and `other` (no duplicates). */
  intersection(other: JsRdd): JsRdd
  /**
   * Apply `f(element, ctx)` to each element.
   *
   * `ctx` is serialized as JSON and injected as `globalThis.__ctx` on the worker.
   * Use this instead of `map` when your function closes over driver-side state —
   * the captured scope is lost when `f.toString()` crosses the wire.
   */
  mapWithContext(ctx: JsonValue, f: (arg0: JsonValue, arg1: JsonValue) => JsonValue): JsRdd
  /**
   * Keep only elements for which `f(element, ctx)` returns truthy.
   *
   * See `mapWithContext` for the captured-context contract.
   */
  filterWithContext(ctx: JsonValue, f: (arg0: JsonValue, arg1: JsonValue) => boolean): JsRdd
  /**
   * Apply `f(element, ctx)` and flatten results.
   *
   * See `mapWithContext` for the captured-context contract.
   */
  flatMapWithContext(ctx: JsonValue, f: (arg0: JsonValue, arg1: JsonValue) => Array<JsonValue>): JsRdd
  /**
   * Apply `f(value, ctx)` only to the value in each `[key, value]` pair.
   *
   * See `mapWithContext` for the captured-context contract.
   */
  mapValuesWithContext(ctx: JsonValue, f: (arg0: JsonValue, arg1: JsonValue) => JsonValue): JsRdd
  /**
   * Reduce pair `[key, value]` elements by key using `f(acc, val, ctx)`.
   *
   * See `mapWithContext` for the captured-context contract.
   */
  reduceByKeyWithContext(ctx: JsonValue, f: (arg0: JsonValue, arg1: JsonValue, arg2: JsonValue) => JsonValue): JsRdd
  /**
   * Aggregate all elements using `f(acc, element, ctx) => acc`. Throws if empty.
   *
   * See `mapWithContext` for the captured-context contract.
   */
  reduceWithContext(ctx: JsonValue, f: (arg0: JsonValue, arg1: JsonValue, arg2: JsonValue) => JsonValue): JsonValue
  /**
   * Aggregate with an initial value using `f(acc, element, ctx) => acc`.
   *
   * See `mapWithContext` for the captured-context contract.
   */
  foldWithContext(ctx: JsonValue, zero: JsonValue, f: (arg0: JsonValue, arg1: JsonValue, arg2: JsonValue) => JsonValue): JsonValue
}

/**
 * SQL execution context backed by DataFusion.
 *
 * Register data sources (CSV, Parquet, JSON) and execute SQL queries.
 *
 * @example
 * ```typescript
 * import { SqlContext } from "@atomic-compute/js";
 *
 * const ctx = new SqlContext();
 * ctx.registerCsv("orders", "orders.csv");
 * const df = ctx.sql("SELECT id, SUM(amount) FROM orders GROUP BY id");
 * const rows = df.collect();
 * ```
 */
export declare class SqlContext {
  /** Create an SQL context. */
  constructor()
  /**
   * Parse and execute a SQL query. Returns a lazy `DataFrame`.
   *
   * The DataFrame is not executed until `collect()`, `show()`, or `count()` is called.
   *
   * @param query - SQL query string.
   */
  sql(query: string): DataFrame
  /**
   * Register a CSV file or directory as a named table.
   *
   * @param name - Table name to use in SQL queries.
   * @param path - Path to the CSV file or directory.
   */
  registerCsv(name: string, path: string): void
  /**
   * Register a Parquet file or directory as a named table.
   *
   * @param name - Table name to use in SQL queries.
   * @param path - Path to the Parquet file or directory.
   */
  registerParquet(name: string, path: string): void
  /**
   * Register a JSONL file or directory as a named table.
   *
   * @param name - Table name to use in SQL queries.
   * @param path - Path to the JSONL file or directory.
   */
  registerJson(name: string, path: string): void
  /**
   * Register an `Rdd` as a named SQL table (the RDD→SQL bridge).
   *
   * The RDD's rows (JS objects) are materialized into an Arrow table using the
   * supplied `schema` (column name → Arrow type string), then registered so SQL
   * can query them. Mirrors `SqlContext.register_rdd` in the Python bindings.
   *
   * @param name - Table name to use in SQL queries.
   * @param rdd - The RDD whose rows become table rows.
   * @param schema - Map of column name to Arrow type (e.g. `{ id: "int64", val: "float64" }`).
   *
   * ```js
   * const rdd = ctx.parallelize([{ id: 1, val: 2.5 }, { id: 2, val: 3.0 }]);
   * sqlCtx.registerRdd("data", rdd, { id: "int64", val: "float64" });
   * const df = sqlCtx.sql("SELECT * FROM data WHERE val > 2.0");
   * ```
   */
  registerRdd(name: string, rdd: JsRdd, schema: Record<string, string>): void
  /** Remove a previously registered table from the catalog. */
  deregisterTable(name: string): void
}
export type JsSqlContext = SqlContext

/**
 * Streaming context for Node.js.
 *
 * ```javascript
 * const ssc = new StreamingContext(0.1);
 * const [stream, queue] = ssc.testQueueStream();
 * const results = [];
 * ssc.foreachRdd(stream.map(x => x * 2), batch => results.push(...batch));
 * queue.push([1, 2, 3]);
 * ssc.runOneBatch();
 * // results === [2, 4, 6]
 * ```
 */
export declare class StreamingContext {
  constructor(batchSecs: number)
  /** Enable checkpointing to `dir`. State is written after each `runOneBatch()`. */
  checkpoint(dir: string): void
  /** Create a queue-backed stream for testing. Returns `[DStream, BatchQueue]`. */
  testQueueStream(): [DStream, BatchQueue]
  /** Create a pair queue-backed stream. Returns `[DStream, BatchQueue]`. */
  testPairQueueStream(): [DStream, BatchQueue]
  /** Register an output operation: `callback(batchArray)` called once per batch. */
  foreachRdd(stream: DStream, callback: (arg: Array<JV>) => void): void
  /** Run exactly one batch tick synchronously. */
  runOneBatch(): void
  /** No-op — use `runOneBatch()` for testing. */
  start(): void
  /** No-op. */
  stop(): void
}
export type JsStreamingContext = StreamingContext

/**
 * Restore a `StreamingContext` from the latest checkpoint written to `dir`.
 *
 * Returns `null` if no checkpoint exists. The caller must re-register all
 * DStreams and output operations on the returned context; the saved
 * `updateStateByKey` state stores are pre-loaded automatically.
 *
 * ```javascript
 * const ssc = streamingContextFromCheckpoint('/tmp/cp') ?? new StreamingContext(1.0);
 * ```
 */
export declare function streamingContextFromCheckpoint(dir: string): StreamingContext | null
